"""Tabla products: active_ingredient eliminada

Revision ID: 246dd4d521b3
Revises: a05f9532f654
Create Date: 2026-01-17 13:05:41.928477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '246dd4d521b3'
down_revision: Union[str, Sequence[str], None] = 'a05f9532f654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('active_ingredient')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_ingredient', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
