"""Tabla products: active_ingredient restaurada

Revision ID: 2ebb50ccee9f
Revises: 246dd4d521b3
Create Date: 2026-01-17 13:09:08.201860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2ebb50ccee9f'
down_revision: Union[str, Sequence[str], None] = '246dd4d521b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_ingredient', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('active_ingredient')

    # ### end Alembic commands ###
